package cmd

import (
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/inference-book/inference-plane/internal/series"
	"github.com/spf13/cobra"
)

var (
	gsRoot            string
	gsTexOut          string
	gsFailOnSimulated bool
)

var genSeriesCmd = &cobra.Command{
	Use:   "gen-series",
	Short: "Regenerate the Part IV value macros from the measurement registry",
	Long: `Reads docs/data/series.yaml and emits book/src/styles/part4-values.tex,
one LaTeX macro per figure chapters 14 and 15 cite.

Chapters cite macros rather than typing numbers, so a figure has exactly one
definition and promoting a placeholder to a measurement is an edit in one
place. Values marked simulated or pending render with a visible [SIMULATED]
marker, because a placeholder that looks like a measurement in the proof is
one that ships.

--fail-on-simulated exits non-zero while any unmeasured value remains, which
is what a release build should run.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		return runGenSeries(gsRoot, gsTexOut, gsFailOnSimulated)
	},
}

func init() {
	rootCmd.AddCommand(genSeriesCmd)
	genSeriesCmd.Flags().StringVar(&gsRoot, "root", ".", "repo root holding docs/data/series.yaml")
	genSeriesCmd.Flags().StringVar(&gsTexOut, "tex-out", "../book/src/styles/part4-values.tex",
		"output path for the LaTeX value macros")
	genSeriesCmd.Flags().BoolVar(&gsFailOnSimulated, "fail-on-simulated", false,
		"exit non-zero if any cited value is still simulated or pending (for release builds)")
}

// texName turns a registry id into a legal LaTeX control sequence. Digits are
// illegal in macro names, so they become words: deterministic beats pretty,
// and the generated file lists every name beside the id it came from.
func texName(id string) string {
	words := map[rune]string{
		'0': "Zero", '1': "One", '2': "Two", '3': "Three", '4': "Four",
		'5': "Five", '6': "Six", '7': "Seven", '8': "Eight", '9': "Nine",
	}
	var b strings.Builder
	b.WriteString("PartIV")
	upper := true
	for _, r := range id {
		switch {
		case r >= '0' && r <= '9':
			b.WriteString(words[r])
			upper = true
		case (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z'):
			s := string(r)
			if upper {
				s = strings.ToUpper(s)
				upper = false
			}
			b.WriteString(s)
		default:
			upper = true
		}
	}
	return b.String()
}

func runGenSeries(root, texOut string, failOnSimulated bool) error {
	reg, err := series.Load(root)
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("% part4-values.tex -- DO NOT EDIT.\n")
	b.WriteString("% Generated by 'iplane gen-series' from iplane's docs/data/series.yaml.\n")
	b.WriteString("%\n")
	b.WriteString("% Every Part IV figure has one definition here. Cite the macro rather than\n")
	b.WriteString("% typing the number, so promoting a placeholder to a measurement is one edit\n")
	b.WriteString("% and the prose cannot drift from the registry.\n%\n")
	b.WriteString("% \\PartIVsimulated marks a value nothing has measured yet. Redefine it to\n")
	b.WriteString("% restyle, but do not redefine it to nothing: it is what stops a placeholder\n")
	b.WriteString("% reading like a measurement in the proof.\n")
	b.WriteString("\\providecommand{\\PartIVsimulated}[1]{#1\\,[SIMULATED]}\n")
	b.WriteString("\\providecommand{\\PartIVpredicted}[1]{#1}\n\n")

	derived := append([]series.Derived(nil), reg.Derived...)
	sort.Slice(derived, func(i, j int) bool { return derived[i].ID < derived[j].ID })

	unmeasured := 0
	for _, d := range derived {
		val := trimFloat(d.Value)
		switch d.Status {
		case series.StatusSimulated, series.StatusPending:
			val = fmt.Sprintf("\\PartIVsimulated{%s}", val)
			unmeasured++
		case series.StatusPredicted:
			// Rendered plainly. The prose is required to say "predicts";
			// a marker here would imply the number is untrustworthy, and
			// a stated prediction is not.
			val = fmt.Sprintf("\\PartIVpredicted{%s}", val)
		}
		if d.Label != "" {
			b.WriteString(fmt.Sprintf("%% %s (%s): %s\n", d.ID, d.Status, d.Label))
		} else {
			b.WriteString(fmt.Sprintf("%% %s (%s)\n", d.ID, d.Status))
		}
		b.WriteString(fmt.Sprintf("\\newcommand{\\%s}{%s}\n\n", texName(d.ID), val))
	}

	if err := os.WriteFile(texOut, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", texOut, err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s: %d values, %d still unmeasured\n", texOut, len(derived), unmeasured)

	if failOnSimulated && unmeasured > 0 {
		for _, d := range derived {
			if d.Status == series.StatusSimulated || d.Status == series.StatusPending {
				fmt.Fprintf(os.Stderr, "  %s is %s: %s\n", d.ID, d.Status, d.Label)
			}
		}
		return fmt.Errorf("%d cited values are not measured; a release build cannot carry them", unmeasured)
	}
	return nil
}

// trimFloat prints a value without trailing zeros, so 32 renders as "32"
// rather than "32.00" where the quantity is a count.
func trimFloat(f float64) string {
	s := strconv.FormatFloat(f, 'f', -1, 64)
	return s
}
